//// Products

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"



export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"



export const CREATE_NEW_PRODUCT_REQUEST = "CREATE_NEW_PRODUCT_REQUEST"
export const CREATE_NEW_PRODUCT_SUCCESS = "CREATE_NEW_PRODUCT_SUCCESS"
export const CREATE_NEW_PRODUCT_FAIL = "CREATE_NEW_PRODUCT_FAIL"
export const CREATE_NEW_PRODUCT_RESET = "CREATE_NEW_PRODUCT_RESET"



export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"



export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"



export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"



export const CLEAR_ERROR = "CLEAR_ERROR"



export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL"


//// Users
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"



export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"


export const FORGOT_PASSWORD_EMAIL_REQUEST = "FORGOT_PASSWORD_EMAIL_REQUEST"
export const FORGOT_PASSWORD_EMAIL = "FORGOT_PASSWORD_EMAIL"
export const FORGOT_PASSWORD_EMAIL_FAIL = "FORGOT_PASSWORD_EMAIL_FAIL"
export const FORGOT_PASSWORD_EMAIL_RESET = "FORGOT_PASSWORD_EMAIL_RESET"


export const RESET_PASSWORD_EMAIL_REQUEST = "RESET_PASSWORD_EMAIL_REQUEST"
export const RESET_PASSWORD_EMAIL = "RESET_PASSWORD_EMAIL"
export const RESET_PASSWORD_EMAIL_FAIL = "RESET_PASSWORD_EMAIL_FAIL"
export const RESET_PASSWORD_EMAIL_RESET = "RESET_PASSWORD_EMAIL_RESET"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER = "LOAD_USER"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"



export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS = "USER_DETAILS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"


export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST"
export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS"
export const ADMIN_ALL_USERS_FAIL = "ADMIN_ALL_USERS_FAIL"



export const ADMIN_DELETE_USERS_REQUEST = "ADMIN_DELETE_USERS_REQUEST"
export const ADMIN_DELETE_USERS_SUCCESS = "ADMIN_DELETE_USERS_SUCCESS"
export const ADMIN_DELETE_USERS_FAIL = "ADMIN_DELETE_USERS_FAIL"
export const ADMIN_DELETE_USERS_RESET = "ADMIN_DELETE_USERS_RESET"


export const ADMIN_UPDATE_USERS_REQUEST = "ADMIN_UPDATE_USERS_REQUEST"
export const ADMIN_UPDATE_USERS_SUCCESS = "ADMIN_UPDATE_USERS_SUCCESS"
export const ADMIN_UPDATE_USERS_FAIL = "ADMIN_UPDATE_USERS_FAIL"
export const ADMIN_UPDATE_USERS_RESET = "ADMIN_UPDATE_USERS_RESET"


export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"




export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"


export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO"


export const CREATE_NEW_ORDER_REQUEST = "CREATE_NEW_ORDER_REQUEST"
export const CREATE_NEW_ORDER = "CREATE_NEW_ORDER"
export const CREATE_NEW_ORDER_FAIL = "CREATE_NEW_ORDER_FAIL"

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST"
export const MY_ORDER = "MY_ORDER"
export const MY_ORDER_FAIL = "MY_ORDER_FAIL"



export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS = "ORDER_DETAILS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"


export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST"
export const ALL_ORDER = "ALL_ORDER"
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL"

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER = "DELETE_ORDER"
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET"



export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER = "UPDATE_ORDER"
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET"